"""
英语复习器 - 数据库文件
存放所有单词、短语、语法题目数据
"""

# ==================== 短语库 ====================
PHRASES = {
    'help sb. with sth.': '帮某人做某事',
    'be good at sth.': '擅长某事',
    'look forward to sth.': '期待某事',
    'take care of sb.': '照顾某人',
    'make friends with sb.': '和某人交朋友',
    'be interested in sth.': '对某事感兴趣',
    'be proud of sth.': '为某事感到自豪',
    'pay attention to sth.': '注意某事',
    'be responsible for sth.': '对某事负责',
    'get rid of sth.': '摆脱某事',
    'be afraid of sth.': '害怕某事',
    'be similar to sth.': '与某事相似',
    'be different from sth.': '与某事不同',
    'be full of sth.': '充满某事',
    'be tired of sth.': '厌倦某事',
    'be famous for sth.': '以某事闻名',
    'be known for sth.': '以某事闻名',
    'be used to sth.': '习惯于某事',
    'be addicted to sth.': '沉迷于某事',
    'remember sb. for sth.': '因某事记住某人',
    'make use of': '利用',
    'prepare for': '为...做准备',
    'take part in': '参加',
    'prepare sth. for sb.': '为某人准备某事',
    'prepare sth. for': '为...把某物准备好',
    'really look forward to sth.': '非常期待某事',
    'really good at sth.': '非常擅长某事',
    'quite proud of sth.': '相当自豪某事',
    'very similar to sth.': '非常相似某事',
    'a lot of': '许多',
    'a few': '一些',
    'a little': '一点点',
    'a couple of': '几个',
    'a variety of': '各种各样的',
    'a number of': '许多',
    'a great deal of': '大量的',
    'a large amount of': '大量的',
    'a wide range of': '广泛的',
}

# ==================== 单词库 ====================
WORDS = {
    'good': '好的',
    'happy': '快乐的',
    'difficult': '困难的',
    'important': '重要的',
    'beautiful': '美丽的',
    'strong': '强壮的',
    'fast': '快速的',
    'easy': '容易的',
    'interesting': '有趣的',
    'friendly': '友好的',
    'kind': '善良的',
    'brave': '勇敢的',
    'smart': '聪明的',
    'funny': '有趣的',
    'lazy': '懒惰的',
    'polite': '有礼貌的',
    'math': '数学',
    'science': '科学',
    'history': '历史',
    'art': '艺术',
    'music': '音乐',
    'literature': '文学',
    'geography': '地理',
    'biology': '生物学',
    'chemistry': '化学',
    'something': '某事',
    'anything': '任何事',
    'everything': '每件事',
    'nothing': '没有事',
    'someone': '某人',
    'anyone': '任何人',
    'everyone': '每个人',
    'nobody': '没有人',
    'around': '在...周围',
    'behind': '在...后面',
    'between': '在...之间',
    'in': '在...里面',
    'outside': '在...外面',
    'under': '在...下面',
    'above': '在...上面',
    'near': '在...附近',
    'far': '远离...',
    'next to': '在...旁边',
    'in front of': '在...前面',
    'beach': '海滩',
    'mountain': '山',
    'river': '河流',
    'forest': '森林',
    'desert': '沙漠',
    'city': '城市',
    'village': '村庄',
    'country': '国家',
    'island': '岛屿',
    'ocean': '海洋',
    'quarter': '四分之一',
    'half': '一半',
    'drama': '戏剧',
    'economics': '经济学',
    'problem': '问题',
    'solution': '解决方案',
    'decision': '决定',
    'example': '例子',
    'exercise': '练习',
    'project': '项目',
    'report': '报告',
    'reporter': '记者',
    'photographer': '摄影师',
    'engineer': '工程师',
    'architect': '建筑师',
    'scientist': '科学家',
    'pilot': '飞行员',
    'cook': '厨师',
    'corner': '角落',
    'locker': '储物柜',
    'field': '田地',
    'garden': '花园',
    'kitchen': '厨房',
    'living room': '客厅',
    'bedroom': '卧室',
    'bathroom': '浴室',
    'dining room': '餐厅',
    'clavichord': '古钢琴',
    'piano': '钢琴',
    'guitar': '吉他',
    'violin': '小提琴',
    'drum': '鼓',
}

# ==================== 语法时态题库 ====================
TENSE_QUESTIONS = {
    '一般现在时': {
        'he () to school every day.(go)': 'goes',
        'They () basketball.(plays)': 'play',
        'She () TV every evening.(watch)': 'watches',
        'My father () to work by car.(drive)': 'drives',
        'The sun () in the east.(rise)': 'rises',
        'We () English on Mondays.(study)': 'study',
        'Tom and Jerry () friends.(be)': 'are',
        "My mother () dinner at 6 o'clock.(make)": 'makes',
        'The cat () on the roof.(sit)': 'sits',
        'I () my homework after school.(do)': 'do',
        'She () very fast.(run)': 'runs',
    },
    '一般过去时': {
        'He () to the park yesterday.(go)': 'went',
        'They () a movie last night.(watch)': 'watched',
        'She () her grandmother last weekend.(visit)': 'visited',
        'My father () to work by bus last Monday.(go)': 'went',
        'The teacher () us a story last class.(tell)': 'told',
        'We () football last Saturday.(play)': 'played',
        'Tom () a letter to his friend yesterday.(write)': 'wrote',
        'My mother () a cake for my birthday last year.(bake)': 'baked',
        'The dog () in the yard yesterday.(run)': 'ran',
        'I () my room last Sunday.(clean)': 'cleaned',
    },
    '现在进行时': {
        'He () TV now.(watch)': 'is watching',
        'They () basketball at the moment.(play)': 'are playing',
        'She () her homework now.(do)': 'is doing',
        'My father () to work now.(drive)': 'is driving',
        'The children () in the park now.(play)': 'are playing',
        'We () English now.(study)': 'are studying',
        'Tom () a book now.(read)': 'is reading',
        'My mother () dinner now.(make)': 'is making',
        'The dog () in the yard now.(run)': 'is running',
        'I () my room now.(clean)': 'am cleaning',
    },
    '过去进行时': {
        'He () TV when I called him.(watch)': 'was watching',
        'They () basketball when it started to rain.(play)': 'were playing',
        'She () her homework when I arrived.(do)': 'was doing',
        'My father () to work when I saw him.(drive)': 'was driving',
        'The children () in the park when I met them.(play)': 'were playing',
        'We () English when the bell rang.(study)': 'were studying',
        'Tom () a book when I entered the room.(read)': 'was reading',
        'My mother () dinner when I got home.(make)': 'was making',
        'The dog () in the yard when I called it.(run)': 'was running',
        'I () my room when the phone rang.(clean)': 'was cleaning',
    },
    '现在完成时': {
        'He () his homework already.(finish)': 'has finished',
        'They () their project.(complete)': 'have completed',
        'She () her book.(read)': 'has read',
        'My father () the report.(write)': 'has written',
        'The children () their games.(play)': 'have played',
        'We () English lessons.(attend)': 'have attended',
        'Tom () his chores.(do)': 'has done',
        'My mother () cooking dinner.(start)': 'has started',
        'The dog () its walk.(take)': 'has taken',
        'I () my room.(clean)': 'have cleaned',
    },
    '过去完成时': {
        'He () his homework before dinner.(finish)': 'had finished',
        'They () their project by last week.(complete)': 'had completed',
        'She () her book before the trip.(read)': 'had read',
        'My father () the report before the meeting.(write)': 'had written',
        'The children () their games before bedtime.(play)': 'had played',
        'We () English lessons before the exam.(attend)': 'had attended',
        'Tom () his chores before going out.(do)': 'had done',
        'My mother () cooking dinner before guests arrived.(start)': 'had started',
        'The dog () its walk before lunch.(take)': 'had taken',
        'I () my room before my friends came over.(clean)': 'had cleaned',
    },
}


def get_all_data():
    """获取所有数据的便捷函数"""
    return {
        'phrases': PHRASES,
        'words': WORDS,
        'tenses': TENSE_QUESTIONS
    }


def add_word(word, meaning):
    """添加新单词到词库"""
    WORDS[word] = meaning


def add_phrase(phrase, meaning):
    """添加新短语到词库"""
    PHRASES[phrase] = meaning


def add_tense_question(tense, question, answer):
    """添加新的语法题目"""
    if tense not in TENSE_QUESTIONS:
        TENSE_QUESTIONS[tense] = {}
    TENSE_QUESTIONS[tense][question] = answer
